- name: Install and start Cockpit
  yum:
    name: cockpit
    state: latest
  become_user: root
        
- name: enable cockpit
  systemd:
    name: cockpit
    state: started
    enabled: yes
  become: true

- name: Allow Cockpit to access the vm
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    insertafter: '#PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  become: yes

- name: Allow root login for cockpit
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    insertafter: '#PermitRootLogin'
    line: 'PermitRootLogin yes'
  notify:
    -restart sshd
  become: yes


- name: Restart sshd
  service: 
    state: restarted
    name: sshd

- name: Allow cockpit on firewalld
  firewalld:
    service: cockpit
    permanent: true
    state: enabled
    zone: public
  become_user: root

- name: Restart firewalld
  service:
    state: restarted
    name: firewalld
  when: "'Cent' in inventory_hostname or 'ansible-host' in inventory_hostname"
  become_user: root
  
- name: Copy vagrant key
  copy:
    src: keys/vagrant
    dest: /home/vagrant/.ssh/
    owner: vagrant
    group: vagrant
    mode: 0600
  when: "'ansible-host' in inventory_hostname"